import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:kpss_soru_bankasi/services/license_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('LicenseService - Ed25519 asymmetric verification end-to-end', () async {
    final mockDeviceId = 'KPSS-8X42-9B1K-77M9';
    SharedPreferences.setMockInitialValues({
      'kpss_unique_device_id': mockDeviceId,
    });

    final service = LicenseService.instance;
    final deviceId = await service.getDeviceId();
    expect(deviceId, equals(mockDeviceId));

    // Initially not activated
    expect(await service.isActivated(), isFalse);

    // Signature generated by private key for KPSS-8X42-9B1K-77M9
    final validKey = 'ACT-_qrx4JH0HpCQ91CpXqZkzoRmrWiEA4U7rTFyvpCVqBDucgrmo8PwiaiU9Ry_PtsqwUdTFnlj_931sbKFKfPYAA';
    final result = await service.activateWithKey(validKey);
    expect(result, isTrue);

    // Now it should be permanently activated
    expect(await service.isActivated(), isTrue);

    // Test with another device: Should be false for another device!
    service.resetForTesting();
    SharedPreferences.setMockInitialValues({
      'kpss_unique_device_id': 'KPSS-9999-8888-7777',
      // Cloned activation token from device 1
      'kpss_activation_signature': '_qrx4JH0HpCQ91CpXqZkzoRmrWiEA4U7rTFyvpCVqBDucgrmo8PwiaiU9Ry_PtsqwUdTFnlj_931sbKFKfPYAA',
    });

    expect(await service.isActivated(), isFalse);
  });
}
